### ISSUE TITLE
Make "download" a list?

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1760]
Sometimes specific download sources for a mod are not availabe like stated in #1758 but the file is mirrored at a different site.

By allowing download to be a list several well-defined mirror locations could be tried before giving up.

Also non-http(s) links like torrent or magnet could be supported in a backwards-compatible way (because unsupported URLs could just be ignored)

Other fields like download_hash would not be touched by this because for the same file there should be no difference for them.

**Comment by HebaruSan** [comment]
Possible duplicate of #487.

**Comment by HebaruSan** [comment]
Additional use case for this from Discord:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/26ccc69c-70b8-4d5b-adda-7f7fd0c8aaaf)

To generate multiple values for `download`, Netkan would need to be able to associate a mod with multiple hosts. I have a dev branch capable of this now, using the `---` document separator from YAML, and merging inflated modules according to `version`:

```yaml
spec_version: v1.32
identifier: SpaceWarp
name: SpaceWarp
$kref: '#/ckan/spacedock/3277'
$vref: '#/ckan/space-warp'
license: MIT
tags:
  - plugin
  - library
depends:
  - name: BepInEx
  - name: UITKforKSP2
install:
  - find: BepInEx
    install_to: GameRoot
    include_only:
      - patchers
      - plugins
---
spec_version: v1.32
identifier: SpaceWarp
name: SpaceWarp
$kref: '#/ckan/github/SpaceWarpDev/SpaceWarp'
x_netkan_version_edit:
  find: 'spacewarp-'
  replace: ''
  strict: false
$vref: '#/ckan/space-warp'
license: MIT
tags:
  - plugin
  - library
depends:
  - name: BepInEx
  - name: UITKforKSP2
install:
  - find: BepInEx
    install_to: GameRoot
    include_only:
      - patchers
      - plugins
```

&rArr;

```json
    "download": [
        "https://spacedock.info/mod/3277/Space%20Warp%20+%20BepInEx/download/1.4.0",
        "https://github.com/SpaceWarpDev/SpaceWarp/releases/download/spacewarp-1.4.0/spacewarp-release-1.4.0.zip"
    ],
```

The complex part is what to do in the client. Clearly some user-configured prioritization would be helpful for users that experience slow downloads from SpaceDock, but a fallback behavior also seems fairly obvious in case of downtimes, with or without prioritization. And of course we're talking about another spec version increment for this.
